# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p5RgCed6c8tD1OT1Go4p5jwndol6DKZf
"""

import random

print("#####   Welcome to the world of HKM   #######")

player1 = input("Name Of Player 1 :\t")
player2= input("Name of Player 2:\t")

print("Welcome mr/mrs {} and {}".format(player1,player2))
print("Let's Start the Game")

"""**Variable**"""

snake= {17 : 7, 54 : 34, 62 : 19, 98 : 79}    # snake key define the head of the snake while value define the tail of the snake
ladder= {3 : 38, 24 : 33, 42 : 93, 72 : 84}   # value define the tail of the ladder while key define the head of the ladder
score1=0   # initial score of player 1        # initial score of player 1
score2=0   # initial score of player 2        # initial score of the player 2
manuallist= list(range(1,21))                 # for manual mode it define that value lie between 1 to 20

"""**Give option to choose the player who want to do first**"""

print("Initial position of player 1 : {}".format(score1))
print("Initial position of player 2 : {}".format(score2))
while True:
  starting_player= input("Enter player name who want to roll dice First:\t")  #starting player
  if starting_player==player1:
      c=1;
      print("First chance goes to {}".format(player1))
      break;
  elif starting_player==player2:
      c=2;
      print("First  chance goes to {}".format(player2))
      break;
  else:
    print("Enter name correctly")

ran=c

"""***Choose between Auto and Manual Mode***"""

while True:
  mode = int(input("press 1 \rfor Auto Mode \n Press 2 \rfor Manual Mode\n"))
  if mode==1 or mode==2:
    break;
  else:
    mode = int(input("press 1 \rfor Auto Mode \n Press 2 \rfor Manual Mode\t"))

"""**If mode equal to 1  for the Manual Mode where you have to choose number between 1 to 20**

**If mode equal to 1  for the Auto Mode where just type "roll" to generate random number between 1 to 6**
"""

print(snake)
print(ladder)

# this is for the Automatic mode
if mode==1:
  print("Welcome to the Auto Mode")
  while score1<=100 and score2<=100:
    if c==1:   # player1 turn to roll the dice
      roll= input("Type roll to roll the dice  Mr.{}:\t".format(player1))
      if roll=="roll":
          choice= random.randint(1,6)
          print("U get {}",format(choice))
          ran=score1   # just keep the reference if in case the number exceed than 100 than just put this value to score 1 again
          score1=score1+choice
  # check whether the score is less than 100 or not in case score greater than 100 in that case donot add
          if score1<=100:
              score1=score1
          else:
            score1=ran
            print("Sorry u need {}".format(100-score1))
             #checking there is the snake at that particular position or not
          for i in snake.keys():
            if i==score1:
                score1=snake[i]
                print("Oh No u are bitten by snake and fall down to {}".format(snake[i]))
                break
          #checking whether there is ladder at that particular position or not
          for i in ladder.keys():
              if i==score1:       
                  score1=score1+ladder[i]
                  if score1 <=100:
                    score1=score1
                  else:
                    score1=100
                  print("Great u got a ladder to {}".format(ladder[i]))
                  break
          print("Current positiion of {} is {}".format(player1,score1))
          print("Current positiion of {} is {}".format(player2,score2))
          if score1==100:
              print("Hurray Mr.{} won the game".format(player1))
              break

          c=2
          print("----------------------------------------------------")
          print("U chance Mr.{}".format(player2))
          
      else:
          print("Type roll to roll the dice")
    elif c==2: # player 2 chance to roll the dice
      roll= input("Type roll to roll the dice  Mr.{}:\t".format(player2))
      if roll=="roll":
          choice= random.randint(1,6)
          print("U get {}",format(choice))
          ran=score2
          score2=score2+choice
          if score2<=100:
              score2=score2
          else:
            score2=ran
            print("Sorry u need {}".format(100-score2))
          for i in snake.keys():
            if i==score2:
                score2=snake[i]
                print("Oh No u are bitten by snake and fall down to {}".format(snake[i]))
                break
          for i in ladder.keys():
              if i==score2:   
                  ran=score2    
                  score2=score2+ladder[i]
                  if score2 <=100:
                    score2=score2
                  else:
                    score2=100
                  print("Great u got a ladder to {}".format(ladder[i]))
                  break
          print("Current positiion of {} is {}".format(player1,score1))
          print("Current positiion of {} is {},{}".format(player2,score2,type(score2)))
          if score2==100:
              print("Hurray Mr.{} won the game".format(player2))
              break
          c=1
          print("----------------------------------------------------")
          print("U chance Mr.{}".format(player1))
      else:
          print("Type roll to roll the dice Mr.{}".format(player2))

  # this is for the manual mode
elif mode==2:
  print("Welcome to the Manual Mode")
  while score1<=100 and score2<=100:
    if c==1:   # player1 turn to choose the number
      roll= int(input("Enter Number between 1 to 20 inclusive 1 and 20 Mr.{}:\t".format(player1)))
      if roll in manuallist:     # check whether number lie between the 1 to 20 or not
          print("U Choice {}",format(roll)) 
          ran=score1
          score1=score1+roll
          # check whether the score is less than 100 or not in case score greater than 100 in that case donot add
          if score1<=100:
              score1=score1 
          else:          
            score1=ran
            print("Sorry u need {}".format(100-score1))
            #checking there is the snake at that particular position or not
          for i in snake.keys():
            if i==score1:
                score1=snake[i]
                print("Oh No u are bitten by snake and fall down to {}".format(snake[i]))
                break
                #checking whether there is ladder at that particular position or not
          for i in ladder.keys():
              if i==score1:       
                  score1=score1+ladder[i]
                  if score1 <=100:
                    score1=score1
                  else:
                    score1=100
                  print("Great u got a ladder to {}".format(ladder[i]))
                  break
          print("Current positiion of {} is {}".format(player1,score1))
          print("Current positiion of {} is {}".format(player2,score2))
          if score1==100:
              print("Hurray Mr.{} won the game".format(player1))
              break

          c=2
          print("----------------------------------------------------")
          print("U chance Mr.{}".format(player2))
          
      else:
          print("Enter Number between 1 to 20")
    elif c==2:   # player1 turn to choose the number
      roll= int(input("Enter Number between 1 to 20 inclusive 1 and 20 Mr.{}:\t".format(player2)))
      if roll in manuallist:    # check whether number lie between the 1 to 20 or not
          print("U get {}",format(roll))
          ran=score2
          score2=score2+roll
             # check whether the score is less than 100 or not in case score greater than 100 in that case donot add
          if score2<=100:
              score2=score2
          else:
            score2=ran
            print("Sorry u need {}".format(100-score2))
          #checking there is the snake at that particular position or not
          for i in snake.keys():
            if i==score2:
                score2=snake[i]
                print("Oh No u are bitten by snake and fall down to {}".format(snake[i]))
                break
          #checking whether there is ladder at that particular position or not
          for i in ladder.keys():
              if i==score2:   
                  ran=score2    
                  score2=score2+ladder[i]
                  if score2 <=100:
                    score2=score2
                  else:
                    score2=100
                  print("Great u got a ladder to {}".format(ladder[i]))
                  break
          print("Current positiion of {} is {}".format(player1,score1))
          print("Current positiion of {} is {}".format(player2,score2))
          if score2==100:
              print("Hurray Mr.{} won the game".format(player2))
              break
          c=1
          print("----------------------------------------------------")
          print("U chance Mr.{}".format(player1))
      else:
          print("Enter Number between 1 to 20 Mr.{}".format(player2))

print("Succesffully Finished")

"""**NAME  :-   VINAYAK KUMAR**
**ROLL NO  :-  1806086** 
**BRANCH   :-  IT**
**ASSIGNMENT - 1**
**EMAIL : 1806086@kiit.ac.in **
"""

